databases:
  - name: pic-resize-db
    databaseName: pic_resize
    user: pic_resize_user

services:
  - type: web
    name: pic-resize
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pic-resize-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: 'False'
      - key: PYTHON_VERSION
        value: '3.11.0'
